version: 2.1
jobs:
  build:
    environment:
      # environment
      CC_TEST_REPORTER_ID: 2bb20e058832f62485904001a0f1f6052dbc95561a97e7a9a6b060434b573a9d
    docker:
      - image: circleci/node:9.10.0
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies={{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command:
            npm install

      - run:
          name: install latest data-modela from repository
          command:
            pwd;
            cd /;
            sudo git clone https://github.com/tutugodfrey/modela;
            cd modela;
            sudo npm install;
            sudo npm test;
            sudo npm link;
            cd ~/app;
            sudo npm link data-modela;
          # - npm install git+https://github.com/tutugodfrey/modela.git#0.0.9
      # - run:
      #     name: install dependencies
      #     command:
      #       npm install git+https://github.com/tutugodfrey/modela.git
      # - run:
      #     name: install java
      #     command:
      #       sudo apt update && sudo apt-get upgrade && sudo apt install apt-get install default-jdk;
      # - run:
      #     name: Download Selenium
      #     command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      # - run:
      #     name: Start Selenium
      #     command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
      #     background: true
      - run:
          name: Setup Code Climate test-reporter
          command:
          # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
            chmod +x ./cc-test-reporter;

      - run:
          name: Run tests and generate code coverage report with nyc
          command:
            ./cc-test-reporter before-build
      - run:
          name: Run Test
          command:
            npm run coverage
      - run:
          name: Send coverage report
          command:
            ./cc-test-reporter  after-build --coverage-input-type lcov
